"""
passport.py – Hearing Passport exporter for OpenHear.

Generates a portable, self-contained "Hearing Passport" from a
:class:`~audiogram.living_profile.LivingHearingProfile`.

The passport is a human-readable Markdown document plus an optional JSON
bundle that can be:

- Carried to any clinic or audiologist.
- Shared with a sound engineer before a concert.
- Imported into any future OpenHear-compatible system.
- Stored alongside a will or medical records.

Everything remains local and under the owner's control.  No cloud required.

Usage::

    from audiogram.living_profile import LivingHearingProfile
    from audiogram.passport import export_passport

    profile = LivingHearingProfile.from_file("audiogram/data/burgess_living_profile.json")
    export_passport(profile, "burgess_passport.md")
    # Also writes burgess_passport.json automatically.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from audiogram.living_profile import LivingHearingProfile

from audiogram.loader import get_severity

_DIVIDER = "─" * 60


def export_passport(
    profile: "LivingHearingProfile",
    output_path: str,
    *,
    include_json_bundle: bool = True,
    include_history: bool = True,
) -> None:
    """Export a Hearing Passport to Markdown (and optionally JSON).

    Args:
        profile:             The profile to export.
        output_path:         Path for the Markdown file.  The ``.md``
                             extension is added if missing.
        include_json_bundle: Also write a ``.json`` companion file.
        include_history:     Include the full change history in both outputs.
    """
    if not output_path.endswith(".md"):
        output_path += ".md"

    md = build_passport_markdown(profile, include_history=include_history)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(md)

    if include_json_bundle:
        json_path = output_path.removesuffix(".md") + ".json"
        bundle = build_passport_bundle(profile, include_history=include_history)
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump(bundle, fh, indent=2, ensure_ascii=False)
            fh.write("\n")


def build_passport_markdown(
    profile: "LivingHearingProfile",
    *,
    include_history: bool = True,
) -> str:
    """Build the Markdown content of a Hearing Passport.

    Args:
        profile:         The profile to document.
        include_history: Include the change history table.

    Returns:
        A Markdown string.
    """
    lines: list[str] = []
    summ = profile.summary()

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append(f"# Hearing Passport — {profile.subject}")
    lines.append("")
    lines.append(
        "> This document is the sovereign hearing data of "
        f"**{profile.subject}**.  It was generated by the OpenHear system "
        "and is released under the Apache 2.0 Licence + Sovereign Use Addendum.  "
        "No cloud, no telemetry, no medical inference."
    )
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| Clinical audiogram date | {profile.clinical_date} |")
    lines.append(f"| Last profile update | {summ.get('last_updated', 'unknown')} |")
    lines.append(f"| Profile history entries | {summ.get('history_entries', 0)} |")
    lines.append("| Format version | `openhear-living-profile-v1` |")
    lines.append("")

    # ── Clinical core ─────────────────────────────────────────────────────────
    lines.append("## Clinical Core (Immutable)")
    lines.append("")
    lines.append(
        "_The values below are measurements of the auditory system.  "
        "They are not modified by user preferences._"
    )
    lines.append("")

    core = profile._data["clinical_core"]  # noqa: SLF001
    lines.append(f"**Source:** {core.get('source', 'N/A')}  ")
    lines.append(f"**Date:** {core.get('date', 'N/A')}  ")
    if core.get("notes"):
        lines.append(f"**Notes:** {core['notes']}  ")
    lines.append("")

    for ear, symbol in [("right", "O"), ("left", "X")]:
        label = f"{'Right' if ear == 'right' else 'Left'} Ear ({symbol})"
        lines.append(f"### {label}")
        lines.append("")
        lines.append("| Frequency (Hz) | Threshold (dB HL) | Severity |")
        lines.append("|---------------:|------------------:|----------|")
        for freq, db in profile.get_thresholds(ear):
            sev = get_severity(db)
            lines.append(f"| {freq} | {db} | {sev} |")
        lines.append("")
        try:
            pta = profile.get_pta(ear)
            lines.append(
                f"**PTA:** {pta:.1f} dB HL — **{get_severity(int(pta))}**"
            )
        except ValueError:
            lines.append("**PTA:** insufficient data")
        lines.append("")

    # ── Gain profile ──────────────────────────────────────────────────────────
    lines.append("## DSP Gain Profile")
    lines.append("")
    lines.append(
        "Gain required at each frequency to bring thresholds to the 20 dB HL "
        "reference level, plus user-preference offsets where set."
    )
    lines.append("")
    lines.append("| Ear | Frequency (Hz) | Clinical Gain (dB) | With Preferences (dB) |")
    lines.append("|-----|---------------:|-------------------:|----------------------:|")
    for ear in ("right", "left"):
        clinical = dict(profile.get_gain_profile(ear, include_preference=False))
        with_pref = dict(profile.get_gain_profile(ear, include_preference=True))
        for freq in sorted(clinical):
            lines.append(
                f"| {ear} | {freq} | +{clinical[freq]} | +{with_pref.get(freq, clinical[freq])} |"
            )
    lines.append("")

    # ── Haptic substitution ───────────────────────────────────────────────────
    weights = profile.get_haptic_weights()
    if weights:
        lines.append("## Haptic Substitution Weights")
        lines.append("")
        lines.append(
            "The OpenHear wristband translates inaudible sounds into tactile vibrations.  "
            "Weights are scaled by the severity of hearing loss at each sound's dominant frequency."
        )
        lines.append("")
        lines.append("| Sound Class | Weight | Notes |")
        lines.append("|-------------|-------:|-------|")
        cls_data = {
            sc["name"]: sc
            for sc in profile._data.get("haptic_layer", {}).get("sound_classes", [])  # noqa: SLF001
        }
        for cls_name, weight in sorted(weights.items(), key=lambda kv: -kv[1]):
            note = cls_data.get(cls_name, {}).get("note", "")
            lines.append(f"| {cls_name} | {weight:.0%} | {note} |")
        lines.append("")

    # ── Context map ───────────────────────────────────────────────────────────
    contexts = profile.list_contexts()
    if contexts:
        lines.append("## Contextual Listening Presets")
        lines.append("")
        lines.append(
            "Presets adjust DSP parameters automatically for different listening environments."
        )
        lines.append("")
        all_ctx = profile._data.get("context_map", {}).get("contexts", [])  # noqa: SLF001
        active = profile._data.get("context_map", {}).get("active_context", "")  # noqa: SLF001
        lines.append("| Name | Label | Active |")
        lines.append("|------|-------|--------|")
        for ctx in all_ctx:
            is_active = "✓" if ctx.get("name") == active else ""
            lines.append(f"| `{ctx.get('name', '')}` | {ctx.get('label', '')} | {is_active} |")
        lines.append("")

    # ── History ───────────────────────────────────────────────────────────────
    if include_history:
        history = profile.get_history()
        if history:
            lines.append("## Change History")
            lines.append("")
            lines.append(
                "Each entry carries a SHA-256 hash of the profile state at the moment "
                "of commitment, compatible with the Burgess Principle."
            )
            lines.append("")
            lines.append("| # | Date | Author | Type | Description |")
            lines.append("|---|------|--------|------|-------------|")
            for entry in history:
                ts = entry.get("timestamp", "")[:10]
                lines.append(
                    f"| {entry.get('version', '')} "
                    f"| {ts} "
                    f"| {entry.get('author', '')} "
                    f"| `{entry.get('change_type', '')}` "
                    f"| {entry.get('description', '')} |"
                )
            lines.append("")

    # ── Sovereignty notice ─────────────────────────────────────────────────────
    notice = profile._data.get("sovereignty_notice", "")  # noqa: SLF001
    if notice:
        lines.append("---")
        lines.append("")
        lines.append(f"_{notice}_")
        lines.append("")

    return "\n".join(lines)


def build_passport_bundle(
    profile: "LivingHearingProfile",
    *,
    include_history: bool = True,
) -> dict:
    """Build a portable JSON bundle representation of the Hearing Passport.

    Strips internal-only fields and produces a clean portable dict.

    Args:
        profile:         The profile to bundle.
        include_history: Include the full change history.

    Returns:
        A plain dict suitable for JSON serialisation.
    """
    summ = profile.summary()
    bundle: dict = {
        "format": "openhear-hearing-passport-v1",
        "subject": profile.subject,
        "clinical_date": profile.clinical_date,
        "last_updated": summ.get("last_updated"),
        "right_pta_db_hl": summ.get("right_pta"),
        "right_severity": summ.get("right_severity"),
        "left_pta_db_hl": summ.get("left_pta"),
        "left_severity": summ.get("left_severity"),
        "clinical_thresholds": {
            "right": profile.get_thresholds("right"),
            "left": profile.get_thresholds("left"),
        },
        "gain_profile_clinical": {
            "right": profile.get_gain_profile("right", include_preference=False),
            "left": profile.get_gain_profile("left", include_preference=False),
        },
        "gain_profile_with_preferences": {
            "right": profile.get_gain_profile("right", include_preference=True),
            "left": profile.get_gain_profile("left", include_preference=True),
        },
        "haptic_weights": profile.get_haptic_weights(),
        "active_context": profile.get_active_context(),
        "sovereignty_notice": profile._data.get("sovereignty_notice", ""),  # noqa: SLF001
    }
    if include_history:
        bundle["history"] = profile.get_history()
    return bundle
